/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author damid
 */
public class RoomAvailability extends javax.swing.JFrame {

    /**
     * Creates new form RoomAvailability
     */
    public RoomAvailability() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jButton1579 = new javax.swing.JButton();
        jButton1580 = new javax.swing.JButton();
        jButton1581 = new javax.swing.JButton();
        jButton1582 = new javax.swing.JButton();
        jButton1583 = new javax.swing.JButton();
        jButton1584 = new javax.swing.JButton();
        jButton1585 = new javax.swing.JButton();
        jButton1586 = new javax.swing.JButton();
        jButton1587 = new javax.swing.JButton();
        jButton1588 = new javax.swing.JButton();
        jButton1589 = new javax.swing.JButton();
        jButton1590 = new javax.swing.JButton();
        jButton1591 = new javax.swing.JButton();
        jButton1592 = new javax.swing.JButton();
        jButton1593 = new javax.swing.JButton();
        jButton1594 = new javax.swing.JButton();
        jButton1595 = new javax.swing.JButton();
        jButton1596 = new javax.swing.JButton();
        jButton1597 = new javax.swing.JButton();
        jButton1598 = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        jButton1599 = new javax.swing.JButton();
        jButton1600 = new javax.swing.JButton();
        jButton1601 = new javax.swing.JButton();
        jButton1602 = new javax.swing.JButton();
        jButton1603 = new javax.swing.JButton();
        jButton1604 = new javax.swing.JButton();
        jButton1605 = new javax.swing.JButton();
        jButton1606 = new javax.swing.JButton();
        jButton1607 = new javax.swing.JButton();
        jButton1608 = new javax.swing.JButton();
        jButton1609 = new javax.swing.JButton();
        jButton1610 = new javax.swing.JButton();
        jButton1611 = new javax.swing.JButton();
        jButton1612 = new javax.swing.JButton();
        jButton1613 = new javax.swing.JButton();
        jButton1614 = new javax.swing.JButton();
        jButton1615 = new javax.swing.JButton();
        jButton1616 = new javax.swing.JButton();
        jButton1617 = new javax.swing.JButton();
        jButton1618 = new javax.swing.JButton();
        jButton1619 = new javax.swing.JButton();
        jButton1620 = new javax.swing.JButton();
        jButton1621 = new javax.swing.JButton();
        jButton1622 = new javax.swing.JButton();
        jButton1623 = new javax.swing.JButton();
        jButton1624 = new javax.swing.JButton();
        jButton1625 = new javax.swing.JButton();
        jButton1626 = new javax.swing.JButton();
        jButton1627 = new javax.swing.JButton();
        jButton1628 = new javax.swing.JButton();
        jButton1629 = new javax.swing.JButton();
        jButton1630 = new javax.swing.JButton();
        jButton1631 = new javax.swing.JButton();
        jButton1632 = new javax.swing.JButton();
        jButton1633 = new javax.swing.JButton();
        jButton1634 = new javax.swing.JButton();
        jButton1635 = new javax.swing.JButton();
        jButton1636 = new javax.swing.JButton();
        jButton1637 = new javax.swing.JButton();
        jButton1638 = new javax.swing.JButton();
        jButton1639 = new javax.swing.JButton();
        jButton1640 = new javax.swing.JButton();
        jButton1641 = new javax.swing.JButton();
        jButton1642 = new javax.swing.JButton();
        jButton1643 = new javax.swing.JButton();
        jButton1644 = new javax.swing.JButton();
        jButton1645 = new javax.swing.JButton();
        jButton1646 = new javax.swing.JButton();
        jButton1647 = new javax.swing.JButton();
        jButton1648 = new javax.swing.JButton();
        jButton1649 = new javax.swing.JButton();
        jButton1650 = new javax.swing.JButton();
        jButton1651 = new javax.swing.JButton();
        jButton1652 = new javax.swing.JButton();
        jButton1653 = new javax.swing.JButton();
        jButton1654 = new javax.swing.JButton();
        jButton1655 = new javax.swing.JButton();
        jButton1656 = new javax.swing.JButton();
        jButton1657 = new javax.swing.JButton();
        jButton1658 = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jButton1659 = new javax.swing.JButton();
        jButton1660 = new javax.swing.JButton();
        jButton1661 = new javax.swing.JButton();
        jButton1662 = new javax.swing.JButton();
        jButton1663 = new javax.swing.JButton();
        jButton1664 = new javax.swing.JButton();
        jButton1665 = new javax.swing.JButton();
        jButton1666 = new javax.swing.JButton();
        jButton1667 = new javax.swing.JButton();
        jButton1668 = new javax.swing.JButton();
        jButton1669 = new javax.swing.JButton();
        jButton1670 = new javax.swing.JButton();
        jButton1671 = new javax.swing.JButton();
        jButton1672 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jButton1673 = new javax.swing.JButton();
        jButton1674 = new javax.swing.JButton();
        jButton1675 = new javax.swing.JButton();
        jButton1676 = new javax.swing.JButton();
        jButton1677 = new javax.swing.JButton();
        jButton1678 = new javax.swing.JButton();
        jButton1679 = new javax.swing.JButton();
        jButton1680 = new javax.swing.JButton();
        jButton1681 = new javax.swing.JButton();
        jButton1682 = new javax.swing.JButton();
        jButton1683 = new javax.swing.JButton();
        jButton1684 = new javax.swing.JButton();
        jButton1685 = new javax.swing.JButton();
        jButton1686 = new javax.swing.JButton();
        jButton1687 = new javax.swing.JButton();
        jButton1688 = new javax.swing.JButton();
        jButton1689 = new javax.swing.JButton();
        jButton1690 = new javax.swing.JButton();
        jButton1691 = new javax.swing.JButton();
        jButton1692 = new javax.swing.JButton();
        jButton1693 = new javax.swing.JButton();
        jButton1694 = new javax.swing.JButton();
        jButton1695 = new javax.swing.JButton();
        jButton1696 = new javax.swing.JButton();
        jButton1697 = new javax.swing.JButton();
        jButton1698 = new javax.swing.JButton();
        jButton1699 = new javax.swing.JButton();
        jButton1700 = new javax.swing.JButton();
        jButton1701 = new javax.swing.JButton();
        jLabel80 = new javax.swing.JLabel();
        jButton1702 = new javax.swing.JButton();
        jButton1703 = new javax.swing.JButton();
        jButton1704 = new javax.swing.JButton();
        jButton1705 = new javax.swing.JButton();
        jButton1706 = new javax.swing.JButton();
        jButton1707 = new javax.swing.JButton();
        jButton1708 = new javax.swing.JButton();
        jButton1709 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel2.setBackground(new java.awt.Color(83, 66, 54));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reservation");

        jButton1.setBackground(new java.awt.Color(83, 66, 54));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Customer Details");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(83, 66, 54));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Room Selection");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(83, 66, 54));
        jButton3.setText("Room Availability");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(83, 66, 54));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Check - In");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(83, 66, 54));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Payment");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(83, 66, 54));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Check Out");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel12.setPreferredSize(new java.awt.Dimension(600, 850));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel75.setText("Room Availability");

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(83, 66, 54));
        jLabel76.setText("Single Room");

        jButton1579.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1579.setText("S1");

        jButton1580.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1580.setText("S1");

        jButton1581.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1581.setText("S1");

        jButton1582.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1582.setText("S1");

        jButton1583.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1583.setText("S1");

        jButton1584.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1584.setText("S1");

        jButton1585.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1585.setText("S1");
        jButton1585.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1585ActionPerformed(evt);
            }
        });

        jButton1586.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1586.setText("S1");

        jButton1587.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1587.setText("S1");

        jButton1588.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1588.setText("S1");

        jButton1589.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1589.setText("S1");

        jButton1590.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1590.setText("S1");

        jButton1591.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1591.setText("S1");

        jButton1592.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1592.setText("S1");

        jButton1593.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1593.setText("S1");

        jButton1594.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1594.setText("S1");

        jButton1595.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1595.setText("S1");

        jButton1596.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1596.setText("S1");

        jButton1597.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1597.setText("S1");

        jButton1598.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1598.setText("S1");

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(83, 66, 54));
        jLabel77.setText("Twin Room");

        jButton1599.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1599.setText("T1");

        jButton1600.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1600.setText("T1");

        jButton1601.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1601.setText("T1");

        jButton1602.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1602.setText("T1");

        jButton1603.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1603.setText("T1");

        jButton1604.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1604.setText("T1");

        jButton1605.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1605.setText("T1");

        jButton1606.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1606.setText("T1");

        jButton1607.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1607.setText("T1");

        jButton1608.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1608.setText("T1");

        jButton1609.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1609.setText("T1");

        jButton1610.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1610.setText("T1");

        jButton1611.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1611.setText("T1");

        jButton1612.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1612.setText("T1");

        jButton1613.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1613.setText("T1");

        jButton1614.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1614.setText("T1");

        jButton1615.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1615.setText("T1");

        jButton1616.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1616.setText("T1");

        jButton1617.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1617.setText("T1");

        jButton1618.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1618.setText("T1");

        jButton1619.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1619.setText("F1");
        jButton1619.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1620.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1620.setText("F1");
        jButton1620.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1621.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1621.setText("F1");
        jButton1621.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1622.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1622.setText("F1");
        jButton1622.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1623.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1623.setText("F1");
        jButton1623.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1624.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1624.setText("F1");
        jButton1624.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1625.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1625.setText("F1");
        jButton1625.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1626.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1626.setText("F1");
        jButton1626.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1627.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1627.setText("F1");
        jButton1627.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1628.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1628.setText("F1");
        jButton1628.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1629.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1629.setText("F1");
        jButton1629.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1630.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1630.setText("F1");
        jButton1630.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1631.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1631.setText("F1");
        jButton1631.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1632.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1632.setText("F1");
        jButton1632.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1633.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1633.setText("F1");
        jButton1633.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1634.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1634.setText("F1");
        jButton1634.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1635.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1635.setText("F1");
        jButton1635.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1636.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1636.setText("F1");
        jButton1636.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1637.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1637.setText("F1");
        jButton1637.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1638.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1638.setText("F1");
        jButton1638.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1639.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1639.setText("F1");
        jButton1639.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1640.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1640.setText("F1");
        jButton1640.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1641.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1641.setText("F1");
        jButton1641.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1642.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1642.setText("F1");
        jButton1642.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1643.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1643.setText("F1");
        jButton1643.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1644.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1644.setText("F1");
        jButton1644.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1645.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1645.setText("F1");
        jButton1645.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1646.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1646.setText("F1");
        jButton1646.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1647.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1647.setText("F1");
        jButton1647.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1648.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1648.setText("F1");
        jButton1648.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1649.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1649.setText("F1");
        jButton1649.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1650.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1650.setText("F1");
        jButton1650.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1651.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1651.setText("F1");
        jButton1651.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1652.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1652.setText("F1");
        jButton1652.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1653.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1653.setText("F1");
        jButton1653.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1654.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1654.setText("F1");
        jButton1654.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1655.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1655.setText("F1");
        jButton1655.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1656.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1656.setText("F1");
        jButton1656.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1657.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1657.setText("F1");
        jButton1657.setPreferredSize(new java.awt.Dimension(45, 23));

        jButton1658.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1658.setText("F1");
        jButton1658.setPreferredSize(new java.awt.Dimension(45, 23));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(83, 66, 54));
        jLabel78.setText("Family Room");

        jButton1659.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1659.setText("C1");

        jButton1660.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1660.setText("C1");

        jButton1661.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1661.setText("C1");

        jButton1662.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1662.setText("C1");

        jButton1663.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1663.setText("C1");

        jButton1664.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1664.setText("C1");

        jButton1665.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1665.setText("C1");

        jButton1666.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1666.setText("C1");

        jButton1667.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1667.setText("C1");

        jButton1668.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1668.setText("C1");

        jButton1669.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1669.setText("C1");

        jButton1670.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1670.setText("C1");

        jButton1671.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1671.setText("C1");

        jButton1672.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1672.setText("C1");

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(83, 66, 54));
        jLabel79.setText("Couple Room");

        jButton1673.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1673.setText("C1");

        jButton1674.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1674.setText("C1");

        jButton1675.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1675.setText("C1");

        jButton1676.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1676.setText("C1");

        jButton1677.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1677.setText("C1");

        jButton1678.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1678.setText("C1");

        jButton1679.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1679.setText("C1");

        jButton1680.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1680.setText("C1");

        jButton1681.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1681.setText("C1");

        jButton1682.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1682.setText("C1");

        jButton1683.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1683.setText("C1");

        jButton1684.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1684.setText("C1");

        jButton1685.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1685.setText("C1");

        jButton1686.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1686.setText("C1");

        jButton1687.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1687.setText("C1");

        jButton1688.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1688.setText("C1");

        jButton1689.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1689.setText("C1");

        jButton1690.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1690.setText("C1");

        jButton1691.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1691.setText("C1");

        jButton1692.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1692.setText("C1");

        jButton1693.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1693.setText("C1");

        jButton1694.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1694.setText("C1");

        jButton1695.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1695.setText("C1");

        jButton1696.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1696.setText("C1");

        jButton1697.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1697.setText("C1");

        jButton1698.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1698.setText("C1");

        jButton1699.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1699.setText("B1");

        jButton1700.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1700.setText("B1");

        jButton1701.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1701.setText("B1");

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(83, 66, 54));
        jLabel80.setText("Bussiness Room");

        jButton1702.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1702.setText("B1");

        jButton1703.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1703.setText("B1");

        jButton1704.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1704.setText("B1");

        jButton1705.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1705.setText("B1");

        jButton1706.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1706.setText("B1");

        jButton1707.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1707.setText("B1");
        jButton1707.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1707ActionPerformed(evt);
            }
        });

        jButton1708.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1708.setText("B1");

        jButton1709.setBackground(new java.awt.Color(83, 66, 54));
        jButton1709.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1709.setForeground(new java.awt.Color(255, 255, 255));
        jButton1709.setText("Next");
        jButton1709.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1709.setBorderPainted(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel75))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel76))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1581, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1580, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1579, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1592, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1591, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1590, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1589, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1588, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1587, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1586, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1584, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1583, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1585, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1582, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1598, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1597, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1596, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1595, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1594, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1593, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel77))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1601, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1600, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1599, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1613, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1612, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1611, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1610, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1609, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1608, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1607, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1605, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1604, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1603, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1602, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1618, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1617, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1616, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1615, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1614, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1606, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel79))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1674, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1677, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1673, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1672, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1671, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1664, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1668, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1676, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1675, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1688, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1687, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1685, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1684, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1683, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1682, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1681, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1680, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1670, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1679, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1678, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1698, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1697, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1696, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1695, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1694, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1693, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1692, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1691, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1690, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1669, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1663, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1662, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1661, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1660, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1659, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1667, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1666, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1665, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1686, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1689, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel78))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1638, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1637, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1636, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1647, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1648, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1622, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1623, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1624, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1621, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1619, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1646, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1645, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1644, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1643, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1642, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1641, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1640, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1639, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1620, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1654, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1651, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1650, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1649, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1658, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1657, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1656, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1655, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1635, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1634, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1633, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1631, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1630, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1629, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1628, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1627, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1626, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1625, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1632, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1652, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton1653, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel80))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1700, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1702, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1699, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1708, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1707, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1706, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1705, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1704, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1703, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1701, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jButton1709, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75)
                .addGap(7, 7, 7)
                .addComponent(jLabel76)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1581)
                    .addComponent(jButton1580)
                    .addComponent(jButton1579)
                    .addComponent(jButton1592)
                    .addComponent(jButton1591)
                    .addComponent(jButton1590)
                    .addComponent(jButton1589)
                    .addComponent(jButton1588)
                    .addComponent(jButton1587)
                    .addComponent(jButton1586))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1584)
                    .addComponent(jButton1583)
                    .addComponent(jButton1585)
                    .addComponent(jButton1582)
                    .addComponent(jButton1598)
                    .addComponent(jButton1597)
                    .addComponent(jButton1596)
                    .addComponent(jButton1595)
                    .addComponent(jButton1594)
                    .addComponent(jButton1593))
                .addGap(18, 18, 18)
                .addComponent(jLabel77)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1601)
                    .addComponent(jButton1600)
                    .addComponent(jButton1599)
                    .addComponent(jButton1613)
                    .addComponent(jButton1612)
                    .addComponent(jButton1611)
                    .addComponent(jButton1610)
                    .addComponent(jButton1609)
                    .addComponent(jButton1608)
                    .addComponent(jButton1607))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1605)
                    .addComponent(jButton1604)
                    .addComponent(jButton1603)
                    .addComponent(jButton1602)
                    .addComponent(jButton1618)
                    .addComponent(jButton1617)
                    .addComponent(jButton1616)
                    .addComponent(jButton1615)
                    .addComponent(jButton1614)
                    .addComponent(jButton1606))
                .addGap(18, 18, 18)
                .addComponent(jLabel79)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1674)
                    .addComponent(jButton1677)
                    .addComponent(jButton1673)
                    .addComponent(jButton1672)
                    .addComponent(jButton1671)
                    .addComponent(jButton1664)
                    .addComponent(jButton1668)
                    .addComponent(jButton1676)
                    .addComponent(jButton1675)
                    .addComponent(jButton1688))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1687)
                    .addComponent(jButton1685)
                    .addComponent(jButton1684)
                    .addComponent(jButton1683)
                    .addComponent(jButton1682)
                    .addComponent(jButton1681)
                    .addComponent(jButton1680)
                    .addComponent(jButton1670)
                    .addComponent(jButton1679)
                    .addComponent(jButton1678))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1698)
                    .addComponent(jButton1697)
                    .addComponent(jButton1696)
                    .addComponent(jButton1695)
                    .addComponent(jButton1694)
                    .addComponent(jButton1693)
                    .addComponent(jButton1692)
                    .addComponent(jButton1691)
                    .addComponent(jButton1690)
                    .addComponent(jButton1669))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1663)
                    .addComponent(jButton1662)
                    .addComponent(jButton1661)
                    .addComponent(jButton1660)
                    .addComponent(jButton1659)
                    .addComponent(jButton1667)
                    .addComponent(jButton1666)
                    .addComponent(jButton1665)
                    .addComponent(jButton1686)
                    .addComponent(jButton1689))
                .addGap(18, 18, 18)
                .addComponent(jLabel78)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1638, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1637, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1636, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1647, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1648, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1622, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1623, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1624, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1621, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1619, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1646, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1645, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1644, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1643, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1642, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1641, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1640, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1639, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1620, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1654, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1651, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1650, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1649, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1658, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1657, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1656, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1655, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1635, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1634, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1633, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1631, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1630, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1629, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1628, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1627, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1626, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1625, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1632, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1652, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1653, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel80)
                .addGap(7, 7, 7)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1700)
                    .addComponent(jButton1702)
                    .addComponent(jButton1699)
                    .addComponent(jButton1708)
                    .addComponent(jButton1707)
                    .addComponent(jButton1706)
                    .addComponent(jButton1705)
                    .addComponent(jButton1704)
                    .addComponent(jButton1703)
                    .addComponent(jButton1701))
                .addGap(18, 18, 18)
                .addComponent(jButton1709, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jScrollPane1.setViewportView(jPanel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new Check_Out().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Check_In().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new RoomSelection().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1585ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1585ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1585ActionPerformed

    private void jButton1707ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1707ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1707ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomAvailability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1579;
    private javax.swing.JButton jButton1580;
    private javax.swing.JButton jButton1581;
    private javax.swing.JButton jButton1582;
    private javax.swing.JButton jButton1583;
    private javax.swing.JButton jButton1584;
    private javax.swing.JButton jButton1585;
    private javax.swing.JButton jButton1586;
    private javax.swing.JButton jButton1587;
    private javax.swing.JButton jButton1588;
    private javax.swing.JButton jButton1589;
    private javax.swing.JButton jButton1590;
    private javax.swing.JButton jButton1591;
    private javax.swing.JButton jButton1592;
    private javax.swing.JButton jButton1593;
    private javax.swing.JButton jButton1594;
    private javax.swing.JButton jButton1595;
    private javax.swing.JButton jButton1596;
    private javax.swing.JButton jButton1597;
    private javax.swing.JButton jButton1598;
    private javax.swing.JButton jButton1599;
    private javax.swing.JButton jButton1600;
    private javax.swing.JButton jButton1601;
    private javax.swing.JButton jButton1602;
    private javax.swing.JButton jButton1603;
    private javax.swing.JButton jButton1604;
    private javax.swing.JButton jButton1605;
    private javax.swing.JButton jButton1606;
    private javax.swing.JButton jButton1607;
    private javax.swing.JButton jButton1608;
    private javax.swing.JButton jButton1609;
    private javax.swing.JButton jButton1610;
    private javax.swing.JButton jButton1611;
    private javax.swing.JButton jButton1612;
    private javax.swing.JButton jButton1613;
    private javax.swing.JButton jButton1614;
    private javax.swing.JButton jButton1615;
    private javax.swing.JButton jButton1616;
    private javax.swing.JButton jButton1617;
    private javax.swing.JButton jButton1618;
    private javax.swing.JButton jButton1619;
    private javax.swing.JButton jButton1620;
    private javax.swing.JButton jButton1621;
    private javax.swing.JButton jButton1622;
    private javax.swing.JButton jButton1623;
    private javax.swing.JButton jButton1624;
    private javax.swing.JButton jButton1625;
    private javax.swing.JButton jButton1626;
    private javax.swing.JButton jButton1627;
    private javax.swing.JButton jButton1628;
    private javax.swing.JButton jButton1629;
    private javax.swing.JButton jButton1630;
    private javax.swing.JButton jButton1631;
    private javax.swing.JButton jButton1632;
    private javax.swing.JButton jButton1633;
    private javax.swing.JButton jButton1634;
    private javax.swing.JButton jButton1635;
    private javax.swing.JButton jButton1636;
    private javax.swing.JButton jButton1637;
    private javax.swing.JButton jButton1638;
    private javax.swing.JButton jButton1639;
    private javax.swing.JButton jButton1640;
    private javax.swing.JButton jButton1641;
    private javax.swing.JButton jButton1642;
    private javax.swing.JButton jButton1643;
    private javax.swing.JButton jButton1644;
    private javax.swing.JButton jButton1645;
    private javax.swing.JButton jButton1646;
    private javax.swing.JButton jButton1647;
    private javax.swing.JButton jButton1648;
    private javax.swing.JButton jButton1649;
    private javax.swing.JButton jButton1650;
    private javax.swing.JButton jButton1651;
    private javax.swing.JButton jButton1652;
    private javax.swing.JButton jButton1653;
    private javax.swing.JButton jButton1654;
    private javax.swing.JButton jButton1655;
    private javax.swing.JButton jButton1656;
    private javax.swing.JButton jButton1657;
    private javax.swing.JButton jButton1658;
    private javax.swing.JButton jButton1659;
    private javax.swing.JButton jButton1660;
    private javax.swing.JButton jButton1661;
    private javax.swing.JButton jButton1662;
    private javax.swing.JButton jButton1663;
    private javax.swing.JButton jButton1664;
    private javax.swing.JButton jButton1665;
    private javax.swing.JButton jButton1666;
    private javax.swing.JButton jButton1667;
    private javax.swing.JButton jButton1668;
    private javax.swing.JButton jButton1669;
    private javax.swing.JButton jButton1670;
    private javax.swing.JButton jButton1671;
    private javax.swing.JButton jButton1672;
    private javax.swing.JButton jButton1673;
    private javax.swing.JButton jButton1674;
    private javax.swing.JButton jButton1675;
    private javax.swing.JButton jButton1676;
    private javax.swing.JButton jButton1677;
    private javax.swing.JButton jButton1678;
    private javax.swing.JButton jButton1679;
    private javax.swing.JButton jButton1680;
    private javax.swing.JButton jButton1681;
    private javax.swing.JButton jButton1682;
    private javax.swing.JButton jButton1683;
    private javax.swing.JButton jButton1684;
    private javax.swing.JButton jButton1685;
    private javax.swing.JButton jButton1686;
    private javax.swing.JButton jButton1687;
    private javax.swing.JButton jButton1688;
    private javax.swing.JButton jButton1689;
    private javax.swing.JButton jButton1690;
    private javax.swing.JButton jButton1691;
    private javax.swing.JButton jButton1692;
    private javax.swing.JButton jButton1693;
    private javax.swing.JButton jButton1694;
    private javax.swing.JButton jButton1695;
    private javax.swing.JButton jButton1696;
    private javax.swing.JButton jButton1697;
    private javax.swing.JButton jButton1698;
    private javax.swing.JButton jButton1699;
    private javax.swing.JButton jButton1700;
    private javax.swing.JButton jButton1701;
    private javax.swing.JButton jButton1702;
    private javax.swing.JButton jButton1703;
    private javax.swing.JButton jButton1704;
    private javax.swing.JButton jButton1705;
    private javax.swing.JButton jButton1706;
    private javax.swing.JButton jButton1707;
    private javax.swing.JButton jButton1708;
    private javax.swing.JButton jButton1709;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
